### ISSUE TITLE
Having the TargetFramework in a Directory.Build.props file at repo root causes errors without much explanation

### ISSUE THREAD

**Issue by anand-raju** [BMuuN/vsts-assemblyinfo-task#283] opened 2022-10-06 00:13 UTC
Having the TargetFramework moved to Directory.Build.props at the root of the repo and not repeated in each csproj file is causing a strange issue in some projects alone:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  </ItemGroup>
  
</Project>
```

```powershell
Processing: D:\a\1\s\src\Foo\Bar\Contoso.csproj
Detected file encoding: iso-8859-2
##[error]Error reading file: null
```

Once I reverted the change, the build started succeeding again.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  
</Project>
```

**Comment by BMuuN** [comment] 2023-03-04 08:46
I'm  unsure why the `<TargetFramework>` is causing issues and I'm unable to replicate this issue.  Can you confirm which version of the task you are running and (if possible) show me the YAML or task parameters?

Also, it looks like you have configured the task to target `.csproj` files.  If you are using a `Directory.Build.props` to centralise your assembly information you may want to consider altering the task to target the `.props` file rather than each individual `.csproj` file.

**Comment by Chaosflo** [comment] 2023-04-11 10:59
Update you task and make sure you target the correct one! 
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#task-versions

I had this error too and an update resolved this issue, I think it's even a duplicate of my issue which I closed now

**Comment by BMuuN** [comment] 2023-05-30 12:02
Closing due to lack of response.  Please feel free to re-open if the above recommendations do not solve your issue.

**Closed by BMuuN** 2023-05-30 12:02 UTC
