### ISSUE TITLE
Problem with setting File version or Product version using vmImage: ubuntu-latest 

### ISSUE THREAD

**Issue by szostki** [BMuuN/vsts-assemblyinfo-task#152] opened 2020-10-13 08:01 UTC
Hi,
Thanks for a great job and for making it easy to manage version while performing CI pipelines.

While building a simple .net core project using vmImage: ubuntu-latest (Azure DevOps Pipelines), I can not change "File version" or "Product version" for executable (exe) files. When executing the same pipeline but with vmImage: windows-latest step for setting version behaves as expected ("File version"/"Product version" is changed).
In both cases dll files have proper "File version"/"Product version". 

Build using ubuntu image:
![image](https://user-images.githubusercontent.com/34010375/95832470-942a5a80-0d3a-11eb-8a19-22606ca93cd3.png)

Build using windows image:
![image](https://user-images.githubusercontent.com/34010375/95832564-b91ecd80-0d3a-11eb-907b-25d75e71d530.png)

Can you help with this somehow?

**Comment by BMuuN** [comment] 2020-10-13 08:37
Hey @szostki any chance you can post the build output/log of the Assembly Info task?
I'm guessing as you're using a different build agent the file paths to the `*.csproj` files maybe incorrect.

**Comment by szostki** [comment] 2020-10-13 10:56
Hi @BMuuN,
No problem. Logs in corresponding files attached below.

Image: ubuntu-latest
[ubuntu.txt](https://github.com/BMuuN/vsts-assemblyinfo-task/files/5370829/ubuntu.txt)


Image: windows-latest
[windows.txt](https://github.com/BMuuN/vsts-assemblyinfo-task/files/5370830/windows.txt)

**Comment by BMuuN** [comment] 2020-11-03 23:24
@szostki did you manage to track down the route of this issue?
Both build outputs state they're setting the attributes correctly.  I've tested with both `ubuntu-16.04` and `ubuntu-20.04` and the task is setting the attributes as expected.

**Comment by szostki** [comment] 2020-11-05 07:30
No... :(
Maybe it is something with ms ubuntu agent.
As a workaround, I'm using windows agent and it works.

**Comment by BMuuN** [comment] 2021-02-08 22:40
Unable to reproduce so closing this issue.

**Closed by BMuuN** 2021-02-08 22:40 UTC
