### ISSUE TITLE
All fields are replaced

### ISSUE THREAD

**Issue by kellyelton** [BMuuN/vsts-assemblyinfo-task#91] opened 2019-02-15 19:12 UTC
Version 2.0.73
.net Standard Project

Before the plugin runs, the csproj contains this

`<PackageIconUrl>\\NetworkShare\lib.ico</PackageIconUrl>`

After it runs, the Icon is removed.

As you can see, I didn't put anything in the IconUrl box, so that it wouldn't replace it.

![image](https://user-images.githubusercontent.com/1356163/52878874-58815c80-3123-11e9-8659-34c35985a719.png)

Additionally, `Authers` and `Owners` was set in the csproj as well.

When I inspected the nuget package, `Authors` and `Owners` was set to the name of the machine tfs built the package on.

**Comment by BMuuN** [comment] 2020-02-10 20:12
I cannot reproduce this.  Can you confirm if it's still an issue?

The task will only populate elements if a value is supplied.  I cannot see how the `Author` element would get populated with the machine name.  Also, the task doesn't populate an `Owner` attribute within the `*.csproj` file.  Are you confusing the `*.csproj` elements with elements within a `*.nuspec` file?

**Comment by BMuuN** [comment] 2020-05-15 09:45
Closing.  Please feel free to re-open if this is still an issue.

**Closed by BMuuN** 2020-05-15 09:45 UTC
Labels: bug
