### ISSUE TITLE
Fail Build If Assembly Info Step is setting Assembly version to a value to larger than windows allows

### ISSUE THREAD

**Issue by sethyost-sigmatek** [BMuuN/vsts-assemblyinfo-task#140] opened 2020-05-13 14:34 UTC
Windows has a limit for each part in the Assembly version of 65535. Can you fail the build if any of the Assembly Version parts are larger than this value?

The File and Product Version fields do NOT have this limitation.

See links below.
[https://stackoverflow.com/questions/1188284/net-large-revision-numbers-in-assemblyversionattribute](https://stackoverflow.com/questions/1188284/net-large-revision-numbers-in-assemblyversionattribute)
[https://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin](https://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin)

**Comment by BMuuN** [comment] 2020-05-17 17:21
Where are you getting the value `65535` from?

**Comment by sethyost-sigmatek** [comment] 2020-05-18 12:19
It is a windows limit because the version parts are using an unsigned int 16. Therefore each version part cant be larger than 65535. So for example this version is not allowed: 1.0.0.65798. You will get compilation errors when you try to set this in Visual Studio. The first link i sent explains this.

**Comment by BMuuN** [comment] 2020-05-18 12:23
I understand that.  I'm trying to figure out where the value `1.0.0.65798` is being generated.  Is this coming from `1.0.0.$(Build.BuildId)` ?

**Comment by sethyost-sigmatek** [comment] 2020-05-18 12:24
Yes.

**Comment by BMuuN** [comment] 2020-05-21 18:00
If any part of the version number contains a value greater than `65535` the msbuild/dotnet task will fail the build and as the extension is not generating this number no change is needed.

I could put a check in the extension but what benefit does that provide over letting the msbuild/dotnet task fail gracefully with the correct error?

**Comment by BMuuN** [comment] 2020-06-06 09:13
Closing as the issue is not related to the extension.

**Closed by BMuuN** 2020-06-06 09:13 UTC
