### ISSUE TITLE
Request for GitHub Actions version

### ISSUE THREAD

**Issue by ptr727** [BMuuN/vsts-assemblyinfo-task#165] opened 2020-11-21 02:08 UTC
I'm converting to GitHub Actions, would really like to use this functionality on Actions, please consider porting.

**Comment by MatthewSteeples** [comment] 2020-12-15 15:12
Duplicate of #135

**Comment by BMuuN** [comment] 2021-02-08 22:38
Closing as it's a duplicate.

**Closed by BMuuN** 2021-02-08 22:38 UTC
