### ISSUE TITLE
Some version fields don't get set

### ISSUE THREAD

**Issue by kellyelton** [BMuuN/vsts-assemblyinfo-task#90] opened 2019-02-15 19:07 UTC
Version 2.0.73
.net Standard Project

![image](https://user-images.githubusercontent.com/1356163/52878565-93cf5b80-3122-11e9-8fa4-c2aa01fc6b59.png)

```2019-02-15T18:56:12.7723251Z Task Parameters...
2019-02-15T18:56:12.7723251Z 	Source folder: C:\agentDefault\_work\1\s\MyLib
2019-02-15T18:56:12.7723251Z 	Source files: MyLib.csproj
2019-02-15T18:56:12.7723251Z 	Insert attributes: false
2019-02-15T18:56:12.7723251Z 	File encoding: auto
2019-02-15T18:56:12.7723251Z 	Write unicode BOM: false
2019-02-15T18:56:12.7723251Z 	Generate NuGet package on build: false
2019-02-15T18:56:12.7723251Z 	Require license acceptance: false
2019-02-15T18:56:12.7723251Z 	Package id: 
2019-02-15T18:56:12.7723251Z 	Package version: $(Date:yy).$(Date:MM).$(Date:dd).73
2019-02-15T18:56:12.7723251Z 	Authors: 
2019-02-15T18:56:12.7723251Z 	Company: 
2019-02-15T18:56:12.7723251Z 	Product: 
2019-02-15T18:56:12.7723251Z 	Description: 
2019-02-15T18:56:12.7723251Z 	Copyright: Copyright © Software $(Date:yyyy)
2019-02-15T18:56:12.7723251Z 	License Url: 
2019-02-15T18:56:12.7723251Z 	Project Url: 
2019-02-15T18:56:12.7723251Z 	Icon Url: 
2019-02-15T18:56:12.7723251Z 	Repository Url: 
2019-02-15T18:56:12.7723251Z 	Repository type: 
2019-02-15T18:56:12.7723251Z 	Tags: 
2019-02-15T18:56:12.7723251Z 	Release notes: 
2019-02-15T18:56:12.7723251Z 	Assembly neutral language: 
2019-02-15T18:56:12.7723251Z 	Assembly version: 
2019-02-15T18:56:12.7723251Z 	Assembly file version: 
2019-02-15T18:56:12.7723251Z 	Informational version: $(Date:yy).$(Date:MM).$(Date:dd).73```

**Comment by BMuuN** [comment] 2019-03-08 19:47
Closing as this is a duplicate of #89

**Closed by BMuuN** 2019-03-08 19:47 UTC
