### ISSUE TITLE
Version not extracted from BuildNumber  with regex

### ISSUE THREAD

**Issue by DavidDeSloovere** [BMuuN/vsts-assemblyinfo-task#96] opened 2019-03-12 09:32 UTC
Just installed this promissing extension and I like how it works. I was already moving into an advanced scenario with build numbers.
I have a build number format `$(Build.DefinitionName)_2.1$(rev:.r).0` that results in a build number like this: `NatchSandbox-Deploy-Linux_2.1.2.0` 
According to the [WIKI](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning#build-number), I was expecting the extension to extract 2.1.2.0 from that, but it took the whole build number instead. Did I misread or am I doing something wrong?
I checked the regex in the source and I don't really see an issue. I also tried without the trailing `.0`.

**Comment by tomaustin700** [comment] 2019-11-29 15:59
This is still an issue.

**Comment by tomaustin700** [comment] 2019-12-04 11:36
Looking at this further I believe the issue is due to line 128 in index.ts. informationalVersion should be set using the regex matched version like how it is done with version and fileVersion i.e.
```csharp
const informationalVersion = model.informationalVersion.match(regex.version);
const informationalVersionValue = informationalVersion && informationalVersion [0] || '';`

model.informationalVersion = utils.setWildcardVersionNumber(informationalVersionValue, model.verBuild, model.verRelease);
```

Would you like a PR raising with this fix?

**Comment by BMuuN** [comment] 2019-12-04 12:11
The version number will be extracted from the build number format however this is only true for the `fileVersion` and `version` fields.  Both fields only allow numeric values in the format _major.minor.build.revision_ (in you example above, 2.1.2.0).

The `packageVersion` and `informationalVersion` can by any string that represents additional version information and is included for informational purposes only.  For this reason the build number is not extracted and the entire build number is used `NatchSandbox-Deploy-Linux_2.1.2.0`.

Additional information surrounding this functionality can be found on the following issues: https://github.com/BMuuN/vsts-assemblyinfo-task/issues/49, https://github.com/BMuuN/vsts-assemblyinfo-task/issues/24, https://github.com/BMuuN/vsts-assemblyinfo-task/issues/68

You can read more about the fields here:
- https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-versioning
- https://docs.microsoft.com/en-us/dotnet/standard/assembly/set-attributes

I can see how the Wiki is misleading around this functionality and I will aim to get this updated a.s.a.p.  Apologies for any confusion this has caused.

**Comment by BMuuN** [comment] 2019-12-04 12:22
Off the top of my head the only way to overcome the issue you're both facing would be changing your build number format, for example:

1) On your build definition create a build variable "AppVersion" and set its value to `2.1.$(Build.BuildId).0`
  (unfortunately `$(rev:.r)` will only work from the Build Number Format filed).
1) On the Build Number Format filed set it to `$(Build.DefinitionName)_$(AppVersion)`
1) On the Assembly Info task set the "Informational Version" field to: `$(AppVersion)`

This approach will ensure your build name includes the version number that's set in your assemblies and your Informational Version will contain the version number only.

**Comment by tomaustin700** [comment] 2019-12-04 13:40
@BMuuN If you set informational version to something that contains text the following error is thrown when running dotnet restore
```
 C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : 'Release_8.22.19333.5' is not a valid version string. (Parameter 'value') [C:\Build Agent\_work\179\s\Identity\Identity\src\Identity.sln]
```
I managed to get around it by writing a powershell script to strip the build name, assign this to a pipeline variable and then use that in the task to set the informational version.

**Comment by BMuuN** [comment] 2019-12-04 16:02
That error is thrown when `Release_8.22.19333.5` is set as the "Package Version".
The build completes successfully when `Release_8.22.19333.5` is set as the "Informational Version".

Can you double check the task output to ensure the Assembly Info task version is v2.0.73

**Comment by BMuuN** [comment] 2020-02-10 19:07
Closing as this is a non-issue as mentioned [above](https://github.com/BMuuN/vsts-assemblyinfo-task/issues/96#issuecomment-561617276).

**Closed by BMuuN** 2020-02-10 19:07 UTC
