### ISSUE TITLE
Source Files stop accepting multiple files

### ISSUE THREAD

**Issue by marceloavf** [BMuuN/vsts-assemblyinfo-task#43] opened 2018-05-28 13:06 UTC
The `Source Files` stop accepting multiple files after this weekend. 

The option was filled like that: 
```
AssemblyInfo.cs
AssemblyInfo.vb
``` 

And we are receiving this warning:
```
2018-05-28T03:29:22.7967226Z 	Net Framework File: AssemblyInfo.csAssemblyInfo.vb
2018-05-28T03:29:22.7967406Z 
2018-05-28T03:29:22.7967466Z 
2018-05-28T03:29:22.8037986Z 	Net Core File: 
2018-05-28T03:29:22.8038186Z 
2018-05-28T03:29:22.8038388Z 
2018-05-28T03:29:22.8051343Z 	Title: ...
...
##[warning]No file found with filename: AssemblyInfo.csAssemblyInfo.vb
```

Last week our build was running normally, this is the log:
```
2018-05-25T21:28:52.0049163Z 	Net Framework File Names: AssemblyInfo.cs
2018-05-25T21:28:52.0049496Z 
2018-05-25T21:28:52.0049602Z 
2018-05-25T21:28:52.0051010Z 	Net Framework File Names: AssemblyInfo.vb
2018-05-25T21:28:52.0051153Z 
2018-05-25T21:28:52.0051269Z 
2018-05-25T21:28:52.0056598Z 	Title: ...
...
2018-05-25T21:28:52.0215204Z Setting .Net Framework assembly info...
2018-05-25T21:28:52.0215512Z 
2018-05-25T21:28:52.0215569Z 
2018-05-25T21:28:53.3566876Z File: C:\agent\_work\11\s\Componentes\My Project\AssemblyInfo.vb
```

We fixed it by creating a task for each file for now,
Thank you.

**Comment by MKatGH** [comment] 2018-05-29 08:39
I had the same issue (putting a comma between each file didn't work), but the latest version (v1.1.38) did resolve this problem for me.

**Comment by rudisugi** [comment] 2018-05-29 19:37
Is there an easy workaround to fix this? I have 40+ build definitions and changing the parameter for each task is very cumbersome. If I delete the 1.1 folder under _tasks, would that force it to use the older version that works?

**Comment by BMuuN** [comment] 2018-05-29 21:28
No deleting the `1.1` folder won't force an older version to download, the latest version will be downloaded (`v1.1.38`).

I'm looking at this issue for you now but I'm unable to reproduce it :(
Files on multiple lines are working and files separated by comma's are working.

Are you able to navigate to the `History` tab of you build definition, scroll down until you find the `Assembly Info` extension and post the value of the `FileNames` property here?  It'll look like this:

```
"inputs": {
  "Path": "$(Build.SourcesDirectory)",
  "FileNames": "AssemblyInfo.cs\nAssemblyInfo.vb\nGlobalInfo.cs",
  "InsertAttributes": "true",
  "Title": "POS",
  "Product": "Point of Sales Application",
  "Description": "A Point of Sales Application Developed by Example Ltd",
  "Company": "Example Ltd",
  "Copyright": "Copyright © $(date:yyyy) Example Ltd",
  "Trademark": "Trademark of Example Ltd",
  "Culture": "",
  "Configuration": "$(BuildConfiguration)",
  "VersionNumber": "$(Build.BuildNumber)",
  "FileVersionNumber": "3.4.*.*",
  "InformationalVersion": "1.1.0-beta2"
}
```

**Comment by ojasp** [comment] 2018-05-29 22:57
Same issue with our build as well. How do we get the latest version?

**Comment by BMuuN** [comment] 2018-05-31 10:52
I've just pushed `v1.1.39` which contains a fix for the above issue.
Let me know if the fix is working for you all.

**Comment by BMuuN** [comment] 2018-06-04 19:38
Closing as the issue has been fixed.

**Closed by BMuuN** 2018-06-04 19:38 UTC
Labels: in progress
