### ISSUE TITLE
C++/CLI support

### ISSUE THREAD

**Issue by jalmaria** [BMuuN/vsts-assemblyinfo-task#107] opened 2019-11-25 12:29 UTC
Thanks for a magnificent extension!
Any chance to get this to support C++/CLI? Should be pretty easy, since it is .NET (default file name is AssemblyInfo.cpp). Sample:
[assembly:AssemblyTitleAttribute("MyAssembly")];
[assembly:AssemblyDescriptionAttribute("MyDescription")];
[assembly:AssemblyConfigurationAttribute("MyConfiguration")]
[assembly:AssemblyCompanyAttribute("MyCompany)];
[assembly:AssemblyProductAttribute("MyProduct")];
[assembly:AssemblyCopyrightAttribute("MyCopyRight")];
[assembly:AssemblyTrademarkAttribute("MyTrademark)];
[assembly:AssemblyCultureAttribute("MyCulture")];

[assembly:AssemblyVersionAttribute("MyAssemblyVersion")];
[assembly:AssemblyInformationalVersionAttribute("MyInformationalVersion")];

**Comment by BMuuN** [comment] 2020-02-10 20:38
Closing as duplicate of #60

**Closed by BMuuN** 2020-02-10 20:38 UTC
Labels: enhancement
