### ISSUE TITLE
Add posibility for other file extensions

### ISSUE THREAD

**Issue by Kmdkca** [BMuuN/vsts-assemblyinfo-task#45] opened 2018-06-04 12:17 UTC
Make it possible to update other extensions. than *.cs, *.vb and *.csproj. e.g. *.h
 
currently i have to add all extensions manually:
$Model.NetFrameworkFileNames += $fileNames | Where-Object { $_ -like "*.h" }

**Comment by BMuuN** [comment] 2019-01-31 21:13
Closing as this is a duplicate of #60

**Closed by BMuuN** 2019-01-31 21:13 UTC
Labels: enhancement
